version: '4.26.1'

services:

  db:
    image: postgres:latest
    container_name: PollingApp
    ports:
      - "5332:5432"
    restart: always
    environment:
      POSTGRES_DB: polling_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password